# Generated by Django 4.2.6 on 2023-11-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambiente',
            old_name='criado_em',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='dispositivo',
            old_name='criado_em',
            new_name='atualizado_em',
        ),
    ]
